import { defineConfig } from 'tsup';
import { preserveDirectivesPlugin } from 'esbuild-plugin-preserve-directives';

export default defineConfig((opts) => ({
    // Multi-entry (file-per-output). This is what lets per-file 'use client'
    // directives survive: the barrel (src/index.ts) is a thin re-export layer
    // with NO directive, while each emitted file keeps its own. A server route
    // importing { getMemcache } from '@collabdt/core' then resolves through the
    // barrel to memcache.js (no directive → server-safe), and a client import
    // of { Button } resolves to Button.js (has 'use client'). A single bundled
    // file cannot do this — one file carries at most one directive.
    entry: [
        'src/**/*.ts',
        'src/**/*.tsx',
        '!src/**/*.test.ts',
        '!src/**/*.test.tsx',
        '!src/**/*.spec.ts',
        '!src/**/*.spec.tsx',
        '!src/**/__tests__/**',
        '!src/**/*.d.ts',
    ],
    format: ['esm'],
    // DTS is generated by a separate `tsc -p tsconfig.build.json` step (see the
    // build script). tsup's bundled DTS (rollup-dts) OOMs when bundling types
    // across ~500 multi-entry outputs; plain tsc emits per-file declarations
    // cheaply and mirrors this JS output structure.
    dts: false,
    // Preserve modules — each source file becomes its own output file with
    // imports kept intact, no shared chunks. Critical for 'use client'
    // correctness: `esbuild-plugin-preserve-directives` keeps directives on
    // individual files but does NOT propagate them onto shared chunks created
    // by splitting, so any barrel import that pulled a 'use client' file
    // through a shared chunk leaked into the server graph and Next refused
    // it ("`ssr: false` is not allowed ... in Server Components"). With
    // bundle:false there are no chunks, the consumer's bundler does the
    // tree-shaking, and every directive lands on the right file.
    splitting: false,
    sourcemap: true,
    // Clean only for one-shot production builds. During --watch, NOT cleaning
    // keeps dist populated across rebuilds so the copied CSS (copy-css.mjs in the
    // dev/dev:link onSuccess) never disappears — kills the "Can't resolve ./auth.css"
    // race where a rebuild wiped dist before CSS was re-copied.
    clean: !opts.watch,
    treeshake: false,
    bundle: false,
    // NOTE: the blanket `banner: { js: "'use client';" }` was removed. It marked
    // the entire bundle as a client boundary, which poisoned server-only exports
    // (memcache, dataset fetchers) imported by the app's API routes. Directives
    // are now preserved per-file by the esbuild plugin below.
    external: [
        // React ecosystem
        'react',
        'react/jsx-runtime',
        'react/jsx-dev-runtime',
        'react-dom',
        'react-dom/client',
        'react-dom/server',
        'react-google-recaptcha',
        'use-sync-external-store',
        'use-sync-external-store/shim',

        // Next.js ecosystem
        'next',
        'next/router',
        'next/link',
        'next/image',
        'next/navigation',
        'next/headers',
        'next/server',
        'next-auth',
        'next-auth/react',
        'next-auth/next',
        'next-intl',
        'next-themes',

        // UI libraries
        'framer-motion',
        'lucide-react',
        'sonner',

        // Data fetching
        'swr',
        'swr/mutation',
        'swr/immutable',

        // Map libraries
        'maplibre-gl',
        'react-map-gl',

        // 3D libraries
        'three',
        'three/examples/jsm/loaders/GLTFLoader',
        'three/examples/jsm/controls/OrbitControls',

        // Radix UI (all packages)
        '@radix-ui/react-accordion',
        '@radix-ui/react-alert-dialog',
        '@radix-ui/react-avatar',
        '@radix-ui/react-checkbox',
        '@radix-ui/react-dialog',
        '@radix-ui/react-dropdown-menu',
        '@radix-ui/react-label',
        '@radix-ui/react-menubar',
        '@radix-ui/react-popover',
        '@radix-ui/react-progress',
        '@radix-ui/react-scroll-area',
        '@radix-ui/react-select',
        '@radix-ui/react-separator',
        '@radix-ui/react-slider',
        '@radix-ui/react-slot',
        '@radix-ui/react-switch',
        '@radix-ui/react-tabs',
        '@radix-ui/react-toggle',
        '@radix-ui/react-toggle-group',
        '@radix-ui/react-tooltip',
        '@radix-ui/react-visually-hidden',

        // Other libraries
        'cmdk',
        'date-fns',
        'react-day-picker',
        '@tanstack/react-table',
        'class-variance-authority',
        'clsx',
        'tailwind-merge',
        '@casl/ability',
        'jspdf',
        'recharts',

        // GIS/Mapping utilities
        'pbf',
        'geojson',
        '@mapbox/vector-tile',
        'proj4',
        '@turf/turf',

        // ThatOpen libraries
        '@thatopen/components',
        '@thatopen/components-front',
        '@thatopen/fragments',
        '@thatopen/ui',
        '@thatopen/ui-obc',

        // Other dependencies
        'web-ifc',
        'dxf-viewer',
        'potree',
        'potree-cdt',
        'potree-core',
        'three-viewport-gizmo',
        '@dnd-kit/core',
        '@dnd-kit/sortable',
        '@dnd-kit/utilities',
    ],
    esbuildPlugins: [
        preserveDirectivesPlugin({
            directives: ['use client', 'use server'],
            include: /\.(js|jsx|ts|tsx)$/,
            exclude: /node_modules/,
        }),
    ],
    esbuildOptions(options) {
        options.jsx = 'automatic';
    },
}));
