import { Coordinates } from 'maplibre-gl'
import { CurrentLocation, LngLat, Location } from './map'
import * as THREE from 'three'
import { ViewerNames } from './dbTypes'

export interface Identified {
  // _id?: string; // Mongo db id
  id: string // id = crypto.randomUUID(); Random id vs id generated by parameters
  name?: string
}

export interface Created extends Identified {
  createdBy?: string
  createdDate?: string
  createdTime?: string
}

export type Theme = 'light' | 'dark'

export interface Modified extends Created {
  modifiedDate?: string
  modifiedBy?: string // User uId
}
export interface SearchParams extends Partial<CurrentLocation> {
  viewer: ViewerNames
  modelId?: string
  buildingId?: string
}

export type CursorType = '' | 'pointer' | 'grab' | 'grabbing' | 'crosshair' | 'copy'

export interface Position extends Partial<LngLat>, Partial<THREE.Vector3> {
  elevation?: number
}

export type FilterState = {
  id: number
  field: string
  fieldType: 'boolean' | 'string' | 'number' | 'date' | 'enum' | null
  operator: 'isTrue' | 'isFalse' | 'contains' | 'equals' | 'startsWith' | 'endsWith' | 'greaterThan' | 'lessThan' | 'between' | 'before' | 'after' | 'inList' | null
  value: boolean | string | number | Date | string[] | null
  secondValue: number | Date | null
}

export enum DataTypes {
  building = 'building',
  site = 'site',
  infrastructure = 'infrastructure',
  file = 'file',
  user = 'user',
}

// Temporary Role names
export enum RoleNames {
  admin = 'Admin',
  user = 'User',
  viewer = 'Viewer',
}

export type FileAction = 'download' | 'view' | 'ghost' | 'move' | 'edit' | 'info' | 'delete'

